const first = [
    "Falafel",
    "Morning",
    "Evening",
    "Midnight",
    "Night",
    "West Coast",
    "The",
    "The Lonely",
    "DJ",
    "Sunflower",
    "Hard",
    "Jazz",
    "The Jazz",
    "Man",
    "The Man",
    "Aberdeen",
    "Miss",
    "Mrs",
    "Mr",
    "All",
    "Urban",
    "Alley",
    "American",
    "Arctic",
    "Backstreet",
    "Bag",
    "Bee",
    "Black Eyed",
    "Blink",
    "Blank",
    "Blue",
    "Blues",
    "Blonde",
    "Bloc",
    "Bowling",
    "Cage",
    "Cage The",
    "Cantina",
    "Band",
    "Crazy",
    "Culture",
    "Daft",
    "Culture",
    "Cutting",
    "Darude",
    "Dead Or",
    "Deep Blue",
    "Death",
    "Electric",
    "Children",
    "Capri-sun",
    "Eiffel",
    "Earth",
    "Fort",
    "Fuck",
    "Foster",
    "Hall &",
    "Gypsy",
    "Knife",
    "Initial",
    "Hello",
    "Emotional",
    "Velvet"
];

const second = [
    "D",
    "182",
    "Sin",
    "Men",
    "Boy",
    "Boys",
    "Girl",
    "Girls",
    "Babe",
    "Babes",
    "Baby",
    "Babies",
    "Cat",
    "Cats",
    "Band",
    "DJs",
    "Emos",
    "Oats",
    "Unit",
    "Lane",
    "Aid",
    "Six",
    "Fire",
    "Gees",
    "Peas",
    "Gang",
    "Frog",
    "Club",
    "Punk",
    "Crew",
    "Word",
    "Wind",
    "World",
    "Minor",
    "Party",
    "Sound",
    "Sounds",
    "Deluxe",
    "Chiefs",
    "Flows",
    "Alive",
    "Trees",
    "for Soup",
    "Falafels",
    "Midnight",
    "Morning",
    "Runners",
    "Wailers",
    "Quartet",
    "Beaches",
    "At Work",
    "Sinners",
    "Wonder",
    "Monkeys",
    "Raiders",
    "Banshee",
    "Cemetery",
    "Traveler",
    "Surfers",
    "Project",
    "Elephant",
    "Mushroom",
    "Sandstorm",
    "Something",
    "Mountains",
    "Superstar",
    "Superstars",
    "Sunflowers",
    "Collective",
    "From Above",
    "Wind & Fire",
    "The Elephant",
    "Sound System",
    "Light Orchestra",
    "And The Gang",
    "And The Machine",
];

module.exports = {
    name: "Band Name Generator",
    usage: "bandname",
    rateLimit: 10,
    detailedHelp: "Creates a brand new band name",
    usageExample: "bandname",
    responseExample: "🎸 🎹 Starting a band? You should call it `Darude The Elephant`",
    categories: ["fun"],
    requiredPermissions: [],
    commands: ["bandname", "bandnames", "bn", "bands"],
    run: async function(message, args, bot){
        message.replyLang("BANDNAME", {first: bot.util.arrayRand(first), second: bot.util.arrayRand(second)});
    },
    test: function(test){
        test('band name generator', function(t){
            const bot = {
                util: {
                    arrayRand: function(array){
                        return array[0];
                    }
                }
            };
            const message = {
                replyLang: function(key){
                      t.is(key, "BANDNAME");
                      return "";
                }
            };
            module.exports.run(message, [], bot);

        })
    }
};