name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm install
        npm i -g ava
        ava test.js
      env:
        CI: true
        SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
    - name: track sentry release
      run: |
        npm install @sentry/cli
        export VERSION=$(node_modules/.bin/sentry-cli releases propose-version)
        node_modules/.bin/sentry-cli releases new -p ocelotbot $VERSION
        node_modules/.bin/sentry-cli  releases set-commits --auto $VERSION
      env:
        SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
